services:

  nginx: 
    image: nginx:1.20.2
    container_name: nginx
    depends_on:
      - backend
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
      
  backend:
    image: onobot
    container_name: backend
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    working_dir: /usr/src/app/
    restart: always
    environment:
      PORT: 5000
      MONGO_URI: mongodb://${ONO_MONGO_ROOT}:${ONO_MONGO_PASSWORD}@onobot_mongo_db:27017/my_db?authSource=admin
    volumes:
      - ./server:/app
      
  database:
    container_name: onobot_mongo_db
    logging:
      driver: none
    image: mongo:5.0.7
    restart: always
    volumes:
      - ono_mongo_volume:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${ONO_MONGO_ROOT}"
      MONGO_INITDB_ROOT_PASSWORD: "${ONO_MONGO_PASSWORD}"


volumes:
  ono_mongo_volume: